### Listar todos os tickets
GET http://localhost:5278/api/tickets

### Criar um ticket
POST http://localhost:5278/api/tickets
Content-Type: application/json

{
  "title": "Meu primeiro ticket",
  "priority": "low",
  "status": "open"
}

### Buscar ticket por id
GET http://localhost:5278/api/tickets/1


### Atualizar ticket
PUT http://localhost:5278/api/tickets/1
Content-Type: application/json

{
  "title": "Ticket atualizado",
  "priority": "high",
  "status": "review"
}

### Mover ticket
PATCH http://localhost:5278/api/tickets/1/move
Content-Type: application/json

{
  "status": "done"
}

### Deletar ticket
DELETE http://localhost:5278/api/tickets/2